apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  database__connection__database: Z2hvc3Q=           # "ghost"
  database__connection__user: cm9vdA==              # "root"
  database__connection__password: ZXhhbXBsZQ==      # "example"
