apiVersion: v1
kind: Secret
metadata:
  name:  mail-secret
data:
   mail__transport: U01UUA== #SMTP
   mail__from: dGVzdEBtYWlsLmNvbQo= # user@your.domain
   mail__options__host: TWFpbGd1bgo= # Mailgun
   mail__options__port: NTg3Cg== #587
   mail__options__auth__user: dGVzdEBtYWlsLmNvbQo= # user@your.domain
   mail__options__auth__pass: dGVzdDEyM3Bhc3N3b3JkMzg0ZGg5MzQ5eWIyOTI4MzIwMzIK # Your SMTP user Password
type: Opaque